using System;
using System.Windows.Input;
using Microsoft.Xna.Framework.Input;

namespace Gemini.Modules.Xna.Services
{
    public abstract class InputMapperBase
    {
        public abstract KeyboardState GetKeyboardState();
        public abstract MouseState GetMouseState();

        protected static Keys MapKey(Key key)
        {
            switch (key)
            {
                case Key.None:
                case Key.Cancel:
                case Key.LineFeed:
                case Key.Clear:
                case Key.Capital:
                case Key.JunjaMode:
                case Key.FinalMode:
                case Key.HanjaMode:
                case Key.ImeAccept:
                case Key.ImeModeChange:
                case Key.Prior:
                case Key.Next:
                case Key.Snapshot:
                case Key.Oem1:
                case Key.Oem2:
                case Key.Oem3:
                case Key.AbntC1:
                case Key.AbntC2:
                case Key.Oem4:
                case Key.Oem5:
                case Key.Oem6:
                case Key.Oem7:
                case Key.Oem102:
                case Key.ImeProcessed:
                case Key.System:
                case Key.OemAttn:
                case Key.OemFinish:
                case Key.OemBackTab:
                case Key.NoName:
                case Key.DeadCharProcessed:
                    return Keys.None;
                case Key.Back:
                    return Keys.Back;
                case Key.Tab:
                    return Keys.Tab;
                case Key.Return:
                    return Keys.Enter;
                case Key.Pause:
                    return Keys.Pause;
                case Key.KanaMode:
                    return Keys.Kana;
                case Key.Escape:
                    return Keys.Escape;
                case Key.ImeConvert:
                    return Keys.ImeConvert;
                case Key.ImeNonConvert:
                    return Keys.ImeNoConvert;
                case Key.Space:
                    return Keys.Space;
                case Key.End:
                    return Keys.End;
                case Key.Home:
                    return Keys.Home;
                case Key.Left:
                    return Keys.Left;
                case Key.Up:
                    return Keys.Up;
                case Key.Right:
                    return Keys.Right;
                case Key.Down:
                    return Keys.Down;
                case Key.Select:
                    return Keys.Select;
                case Key.Print:
                    return Keys.Print;
                case Key.Execute:
                    return Keys.Execute;
                case Key.Insert:
                    return Keys.Insert;
                case Key.Delete:
                    return Keys.Delete;
                case Key.Help:
                    return Keys.Help;
                case Key.D0:
                    return Keys.D0;
                case Key.D1:
                    return Keys.D1;
                case Key.D2:
                    return Keys.D2;
                case Key.D3:
                    return Keys.D3;
                case Key.D4:
                    return Keys.D4;
                case Key.D5:
                    return Keys.D5;
                case Key.D6:
                    return Keys.D6;
                case Key.D7:
                    return Keys.D7;
                case Key.D8:
                    return Keys.D8;
                case Key.D9:
                    return Keys.D9;
                case Key.A:
                    return Keys.A;
                case Key.B:
                    return Keys.B;
                case Key.C:
                    return Keys.C;
                case Key.D:
                    return Keys.D;
                case Key.E:
                    return Keys.E;
                case Key.F:
                    return Keys.F;
                case Key.G:
                    return Keys.G;
                case Key.H:
                    return Keys.H;
                case Key.I:
                    return Keys.I;
                case Key.J:
                    return Keys.J;
                case Key.K:
                    return Keys.K;
                case Key.L:
                    return Keys.L;
                case Key.M:
                    return Keys.M;
                case Key.N:
                    return Keys.N;
                case Key.O:
                    return Keys.O;
                case Key.P:
                    return Keys.P;
                case Key.Q:
                    return Keys.Q;
                case Key.R:
                    return Keys.R;
                case Key.S:
                    return Keys.S;
                case Key.T:
                    return Keys.T;
                case Key.U:
                    return Keys.U;
                case Key.V:
                    return Keys.V;
                case Key.W:
                    return Keys.W;
                case Key.X:
                    return Keys.X;
                case Key.Y:
                    return Keys.Y;
                case Key.Z:
                    return Keys.Z;
                case Key.LWin:
                    return Keys.LeftWindows;
                case Key.RWin:
                    return Keys.RightWindows;
                case Key.Apps:
                    return Keys.Apps;
                case Key.Sleep:
                    return Keys.Sleep;
                case Key.NumPad0:
                    return Keys.NumPad0;
                case Key.NumPad1:
                    return Keys.NumPad1;
                case Key.NumPad2:
                    return Keys.NumPad2;
                case Key.NumPad3:
                    return Keys.NumPad3;
                case Key.NumPad4:
                    return Keys.NumPad4;
                case Key.NumPad5:
                    return Keys.NumPad5;
                case Key.NumPad6:
                    return Keys.NumPad6;
                case Key.NumPad7:
                    return Keys.NumPad7;
                case Key.NumPad8:
                    return Keys.NumPad8;
                case Key.NumPad9:
                    return Keys.NumPad9;
                case Key.Multiply:
                    return Keys.Multiply;
                case Key.Add:
                    return Keys.Add;
                case Key.Separator:
                    return Keys.Separator;
                case Key.Subtract:
                    return Keys.Subtract;
                case Key.Decimal:
                    return Keys.Decimal;
                case Key.Divide:
                    return Keys.Divide;
                case Key.F1:
                    return Keys.F1;
                case Key.F2:
                    return Keys.F2;
                case Key.F3:
                    return Keys.F3;
                case Key.F4:
                    return Keys.F4;
                case Key.F5:
                    return Keys.F5;
                case Key.F6:
                    return Keys.F6;
                case Key.F7:
                    return Keys.F7;
                case Key.F8:
                    return Keys.F8;
                case Key.F9:
                    return Keys.F9;
                case Key.F10:
                    return Keys.F10;
                case Key.F11:
                    return Keys.F11;
                case Key.F12:
                    return Keys.F12;
                case Key.F13:
                    return Keys.F13;
                case Key.F14:
                    return Keys.F14;
                case Key.F15:
                    return Keys.F15;
                case Key.F16:
                    return Keys.F16;
                case Key.F17:
                    return Keys.F17;
                case Key.F18:
                    return Keys.F18;
                case Key.F19:
                    return Keys.F19;
                case Key.F20:
                    return Keys.F20;
                case Key.F21:
                    return Keys.F21;
                case Key.F22:
                    return Keys.F22;
                case Key.F23:
                    return Keys.F23;
                case Key.F24:
                    return Keys.F24;
                case Key.NumLock:
                    return Keys.NumLock;
                case Key.Scroll:
                    return Keys.Scroll;
                case Key.LeftShift:
                    return Keys.LeftShift;
                case Key.RightShift:
                    return Keys.RightShift;
                case Key.LeftCtrl:
                    return Keys.LeftControl;
                case Key.RightCtrl:
                    return Keys.RightControl;
                case Key.LeftAlt:
                    return Keys.LeftAlt;
                case Key.RightAlt:
                    return Keys.RightAlt;
                case Key.BrowserBack:
                    return Keys.BrowserBack;
                case Key.BrowserForward:
                    return Keys.BrowserForward;
                case Key.BrowserRefresh:
                    return Keys.BrowserRefresh;
                case Key.BrowserStop:
                    return Keys.BrowserStop;
                case Key.BrowserSearch:
                    return Keys.BrowserSearch;
                case Key.BrowserFavorites:
                    return Keys.BrowserFavorites;
                case Key.BrowserHome:
                    return Keys.BrowserHome;
                case Key.VolumeMute:
                    return Keys.VolumeMute;
                case Key.VolumeDown:
                    return Keys.VolumeDown;
                case Key.VolumeUp:
                    return Keys.VolumeUp;
                case Key.MediaNextTrack:
                    return Keys.MediaNextTrack;
                case Key.MediaPreviousTrack:
                    return Keys.MediaPreviousTrack;
                case Key.MediaStop:
                    return Keys.MediaStop;
                case Key.MediaPlayPause:
                    return Keys.MediaPlayPause;
                case Key.LaunchMail:
                    return Keys.LaunchMail;
                case Key.SelectMedia:
                    return Keys.SelectMedia;
                case Key.LaunchApplication1:
                    return Keys.LaunchApplication1;
                case Key.LaunchApplication2:
                    return Keys.LaunchApplication2;
                case Key.OemPlus:
                    return Keys.OemPlus;
                case Key.OemComma:
                    return Keys.OemComma;
                case Key.OemMinus:
                    return Keys.OemMinus;
                case Key.OemPeriod:
                    return Keys.OemPeriod;
                case Key.Oem8:
                    return Keys.Oem8;
                case Key.OemCopy:
                    return Keys.OemCopy;
                case Key.OemAuto:
                    return Keys.OemAuto;
                case Key.OemEnlw:
                    return Keys.OemEnlW;
                case Key.Attn:
                    return Keys.Attn;
                case Key.CrSel:
                    return Keys.Crsel;
                case Key.ExSel:
                    return Keys.Exsel;
                case Key.EraseEof:
                    return Keys.EraseEof;
                case Key.Play:
                    return Keys.Play;
                case Key.Zoom:
                    return Keys.Zoom;
                case Key.Pa1:
                    return Keys.Pa1;
                case Key.OemClear:
                    return Keys.OemClear;
                default:
                    throw new ArgumentOutOfRangeException("key");
            }
        }

        protected static ButtonState MapButtonState(MouseButtonState mouseButtonState)
        {
            if (mouseButtonState == MouseButtonState.Pressed)
                return ButtonState.Pressed;
            return ButtonState.Released;
        }
    }
}