//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Modules.CodeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Modules.CodeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  File.
        /// </summary>
        public static string EditorProviderFileSuffix {
            get {
                return ResourceManager.GetString("EditorProviderFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Editor.
        /// </summary>
        public static string SettingsPageCodeEditor {
            get {
                return ResourceManager.GetString("SettingsPageCodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show End Of Line.
        /// </summary>
        public static string ShowEndOfLineCommandText {
            get {
                return ResourceManager.GetString("ShowEndOfLineCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the visibility of end-of-line characters..
        /// </summary>
        public static string ShowEndOfLineCommandToolTip {
            get {
                return ResourceManager.GetString("ShowEndOfLineCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Numbers.
        /// </summary>
        public static string ShowLineNumbersCommandText {
            get {
                return ResourceManager.GetString("ShowLineNumbersCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the visibility of line bumbers..
        /// </summary>
        public static string ShowLineNumbersCommandToolTip {
            get {
                return ResourceManager.GetString("ShowLineNumbersCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Spaces.
        /// </summary>
        public static string ShowSpacesCommandText {
            get {
                return ResourceManager.GetString("ShowSpacesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the visibility of space characters..
        /// </summary>
        public static string ShowSpacesCommandToolTip {
            get {
                return ResourceManager.GetString("ShowSpacesCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tabs.
        /// </summary>
        public static string ShowTabsCommandText {
            get {
                return ResourceManager.GetString("ShowTabsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the visibility of tab characters..
        /// </summary>
        public static string ShowTabsCommandToolTip {
            get {
                return ResourceManager.GetString("ShowTabsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string WordWrapCommandText {
            get {
                return ResourceManager.GetString("WordWrapCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Word Wrap mode..
        /// </summary>
        public static string WordWrapCommandToolTip {
            get {
                return ResourceManager.GetString("WordWrapCommandToolTip", resourceCulture);
            }
        }
    }
}
