//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Modules.Inspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Modules.Inspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0} from {1} to {2}.
        /// </summary>
        public static string ChangeObjectValueActionFormat {
            get {
                return ResourceManager.GetString("ChangeObjectValueActionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ColorEditorAdvanced {
            get {
                return ResourceManager.GetString("ColorEditorAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Colors.
        /// </summary>
        public static string ColorEditorAvailableColors {
            get {
                return ResourceManager.GetString("ColorEditorAvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Colors.
        /// </summary>
        public static string ColorEditorRecentColors {
            get {
                return ResourceManager.GetString("ColorEditorRecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ColorEditorStandard {
            get {
                return ResourceManager.GetString("ColorEditorStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colors.
        /// </summary>
        public static string ColorEditorStandardColors {
            get {
                return ResourceManager.GetString("ColorEditorStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string InspectorBuilderMiscellaneous {
            get {
                return ResourceManager.GetString("InspectorBuilderMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string InspectorDisplayName {
            get {
                return ResourceManager.GetString("InspectorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all ⟲.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset {0} from {1} to {2}.
        /// </summary>
        public static string ResetObjectValueActionFormat {
            get {
                return ResourceManager.GetString("ResetObjectValueActionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⟲.
        /// </summary>
        public static string ResetSymbol {
            get {
                return ResourceManager.GetString("ResetSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetToolTip {
            get {
                return ResourceManager.GetString("ResetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_nspector.
        /// </summary>
        public static string ViewInspectorCommandText {
            get {
                return ResourceManager.GetString("ViewInspectorCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string ViewInspectorCommandToolTip {
            get {
                return ResourceManager.GetString("ViewInspectorCommandToolTip", resourceCulture);
            }
        }
    }
}
