//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to set value: {0}.
        /// </summary>
        public static string AdvancedSliderCommitErrorFormat {
            get {
                return ResourceManager.GetString("AdvancedSliderCommitErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Supported Files.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Redo.
        /// </summary>
        public static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string EditRedoCommandToolTip {
            get {
                return ResourceManager.GetString("EditRedoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Undo.
        /// </summary>
        public static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string EditUndoCommandToolTip {
            get {
                return ResourceManager.GetString("EditUndoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close.
        /// </summary>
        public static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string FileCloseCommandToolTip {
            get {
                return ResourceManager.GetString("FileCloseCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E_xit.
        /// </summary>
        public static string FileExitCommandText {
            get {
                return ResourceManager.GetString("FileExitCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string FileExitCommandToolTip {
            get {
                return ResourceManager.GetString("FileExitCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _New.
        /// </summary>
        public static string FileNewCommandText {
            get {
                return ResourceManager.GetString("FileNewCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        internal static string FileNewCommandToolTip {
            get {
                return ResourceManager.GetString("FileNewCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Untitled {0}.
        /// </summary>
        public static string FileNewUntitled {
            get {
                return ResourceManager.GetString("FileNewUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Open.
        /// </summary>
        public static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string FileOpenCommandToolTip {
            get {
                return ResourceManager.GetString("FileOpenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Files.
        /// </summary>
        internal static string FileRecentFilesCommandText {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Files.
        /// </summary>
        internal static string FileRecentFilesCommandToolTip {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save All.
        /// </summary>
        internal static string FileSaveAllCommandText {
            get {
                return ResourceManager.GetString("FileSaveAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save All.
        /// </summary>
        internal static string FileSaveAllCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAllCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save _As....
        /// </summary>
        public static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save As.
        /// </summary>
        public static string FileSaveAsCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        public static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string FileSaveCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Help.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        public static string HistoryDisplayName {
            get {
                return ResourceManager.GetString("HistoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initial State.
        /// </summary>
        public static string HistoryInitialState {
            get {
                return ResourceManager.GetString("HistoryInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto hide main menu.
        /// </summary>
        public static string MainMenuSettingsAutoHideMainMenu {
            get {
                return ResourceManager.GetString("MainMenuSettingsAutoHideMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Theme:.
        /// </summary>
        public static string MainMenuSettingsColorTheme {
            get {
                return ResourceManager.GetString("MainMenuSettingsColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string MainMenuSettingsLanguage {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requires restart.
        /// </summary>
        public static string MainMenuSettingsLanguageRestart {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Default Title].
        /// </summary>
        public static string MainWindowDefaultTitle {
            get {
                return ResourceManager.GetString("MainWindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes to the {0} &quot;{1}&quot; before closing?.
        /// </summary>
        internal static string SaveChangesBeforeClosingMessage {
            get {
                return ResourceManager.GetString("SaveChangesBeforeClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string SettingsDisplayName {
            get {
                return ResourceManager.GetString("SettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Environment.
        /// </summary>
        public static string SettingsPathEnvironment {
            get {
                return ResourceManager.GetString("SettingsPathEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue.
        /// </summary>
        public static string ThemeBlueName {
            get {
                return ResourceManager.GetString("ThemeBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string ThemeDarkName {
            get {
                return ResourceManager.GetString("ThemeDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string ThemeLightName {
            get {
                return ResourceManager.GetString("ThemeLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        public static string ToolBarStandard {
            get {
                return ResourceManager.GetString("ToolBarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string ToolboxCategory {
            get {
                return ResourceManager.GetString("ToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbox.
        /// </summary>
        public static string ToolboxDisplayName {
            get {
                return ResourceManager.GetString("ToolboxDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Tools.
        /// </summary>
        public static string ToolsMenuText {
            get {
                return ResourceManager.GetString("ToolsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Options.
        /// </summary>
        public static string ToolsOptionsCommandText {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string ToolsOptionsCommandToolTip {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Screen.
        /// </summary>
        internal static string ViewFullScreenCommandText {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Screen.
        /// </summary>
        internal static string ViewFullScreenCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _History.
        /// </summary>
        public static string ViewHistoryCommandText {
            get {
                return ResourceManager.GetString("ViewHistoryCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        public static string ViewHistoryCommandToolTip {
            get {
                return ResourceManager.GetString("ViewHistoryCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbo_x.
        /// </summary>
        public static string ViewToolboxCommandText {
            get {
                return ResourceManager.GetString("ViewToolboxCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbox.
        /// </summary>
        public static string ViewToolboxCommandToolTip {
            get {
                return ResourceManager.GetString("ViewToolboxCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Window.
        /// </summary>
        public static string WindowMenuText {
            get {
                return ResourceManager.GetString("WindowMenuText", resourceCulture);
            }
        }
    }
}
