//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set value: {0}.
        /// </summary>
        public static string AdvancedSliderCommitErrorFormat {
            get {
                return ResourceManager.GetString("AdvancedSliderCommitErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoCommandToolTip {
            get {
                return ResourceManager.GetString("EditRedoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoCommandToolTip {
            get {
                return ResourceManager.GetString("EditUndoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCloseCommandToolTip {
            get {
                return ResourceManager.GetString("FileCloseCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string FileExitCommandText {
            get {
                return ResourceManager.GetString("FileExitCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileExitCommandToolTip {
            get {
                return ResourceManager.GetString("FileExitCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string FileNewCommandText {
            get {
                return ResourceManager.GetString("FileNewCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileNewCommandToolTip {
            get {
                return ResourceManager.GetString("FileNewCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        public static string FileNewUntitled {
            get {
                return ResourceManager.GetString("FileNewUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenCommandToolTip {
            get {
                return ResourceManager.GetString("FileOpenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string FileRecentFilesCommandText {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string FileRecentFilesCommandToolTip {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string FileSaveAllCommandText {
            get {
                return ResourceManager.GetString("FileSaveAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string FileSaveAllCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAllCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string FileSaveAsCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSaveCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryDisplayName {
            get {
                return ResourceManager.GetString("HistoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial State.
        /// </summary>
        public static string HistoryInitialState {
            get {
                return ResourceManager.GetString("HistoryInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide main menu.
        /// </summary>
        public static string MainMenuSettingsAutoHideMainMenu {
            get {
                return ResourceManager.GetString("MainMenuSettingsAutoHideMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme:.
        /// </summary>
        public static string MainMenuSettingsColorTheme {
            get {
                return ResourceManager.GetString("MainMenuSettingsColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string MainMenuSettingsLanguage {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires restart.
        /// </summary>
        public static string MainMenuSettingsLanguageRestart {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default Title].
        /// </summary>
        public static string MainWindowDefaultTitle {
            get {
                return ResourceManager.GetString("MainWindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the {0} &quot;{1}&quot; before closing?.
        /// </summary>
        public static string SaveChangesBeforeClosingMessage {
            get {
                return ResourceManager.GetString("SaveChangesBeforeClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SettingsDisplayName {
            get {
                return ResourceManager.GetString("SettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string SettingsPathEnvironment {
            get {
                return ResourceManager.GetString("SettingsPathEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string ThemeBlueName {
            get {
                return ResourceManager.GetString("ThemeBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDarkName {
            get {
                return ResourceManager.GetString("ThemeDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLightName {
            get {
                return ResourceManager.GetString("ThemeLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ToolBarStandard {
            get {
                return ResourceManager.GetString("ToolBarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ToolboxCategory {
            get {
                return ResourceManager.GetString("ToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string ToolboxDisplayName {
            get {
                return ResourceManager.GetString("ToolboxDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string ToolsMenuText {
            get {
                return ResourceManager.GetString("ToolsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string ToolsOptionsCommandText {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ToolsOptionsCommandToolTip {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string ViewFullScreenCommandText {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string ViewFullScreenCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _History.
        /// </summary>
        public static string ViewHistoryCommandText {
            get {
                return ResourceManager.GetString("ViewHistoryCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ViewHistoryCommandToolTip {
            get {
                return ResourceManager.GetString("ViewHistoryCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbo_x.
        /// </summary>
        public static string ViewToolboxCommandText {
            get {
                return ResourceManager.GetString("ViewToolboxCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string ViewToolboxCommandToolTip {
            get {
                return ResourceManager.GetString("ViewToolboxCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string WindowMenuText {
            get {
                return ResourceManager.GetString("WindowMenuText", resourceCulture);
            }
        }
    }
}
